#!/bin/sh
##
APP=$1

##
##
sys_host_id() {
   SYS_HOST_ID=$( curl -s --connect-timeout 5 http://169.254.169.254/latest/meta-data/local-hostname )
   if [ -z "${HOST_ID}" ] ;
   then
      SYS_HOST_ID=$( hostname || echo "localhost.localdomain" )
   fi
}

##
##
sys_node_id() {
   if [ -f /.dockerenv ]; then
      ## cpu has multiple formats
      ## 2:cpu:/ecs/9eed4eed-e128-441a-a885-2d0a871fa498/baf77f385c73d3426fc6648e62bd20f58bf3d88036acf733d8513d923b109005
      ## 2:cpu:/docker/05108d972fb3bb1844d73718cf24e50a955af2b49eda6d143ba9b001a3612567
      SYS_NODE_ID=$( cat /proc/self/cgroup | grep "cpu:/" | sed 's/\([0-9]\):cpu:.*\/[^\/]*\///g' | head -c 12 )
   else
      SYS_NODE_ID=$( base64 /dev/urandom | tr -dc 'a-f0-9' | head -c 12 )
   fi  
}

##
##
erl_node_id() {
   USR_NODE_ID=${NODE%@*}
   USR_HOST_ID=${NODE#*@}
   if [ -z "${USR_NODE_ID}" ] ;
   then
      ERL_NODE="${SYS_NODE_ID}@${SYS_HOST_ID}"
   else
      if [ "${USR_NODE_ID}" == "${USR_HOST_ID}" ] ;
      then
         ERL_NODE="${USR_NODE_ID}@${SYS_HOST_ID}"
      else
         ERL_NODE="${USR_NODE_ID}@${USR_HOST_ID}"
      fi
   fi
}


sys_host_id
sys_node_id
erl_node_id

##
##
export HOME=/root
export RELX_REPLACE_OS_VARS=true
export CODE_LOADING_MODE=interactive
export ERL_NODE

/rel/${APP}/bin/${APP} foreground
